# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: blog build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      - run: npm run build

      - name: Tencent COS Action
        # You may pin to the exact commit or the version.
        # uses: zkqiang/tencent-cos-action@0caa1b4f62d8531085abd73ac5c2f62570609752
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          # COSCMD args, detail: https://cloud.tencent.com/document/product/436/10976
          args: upload -r  .vuepress/dist/  .
          # Tencent cloud SecretId, from: https://console.cloud.tencent.com/cam/capi
          secret_id: ${{ secrets.SECRETID }}
          # Tencent cloud SecretKey, from: https://console.cloud.tencent.com/cam/capi
          secret_key: ${{ secrets.SECRETKEY }}
          # COS bucket name
          bucket: ${{ secrets.BUCKET }}
          # COS bucket region, detail: https://cloud.tencent.com/document/product/436/6224
          region: ${{ secrets.REGION }}